version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Test-karthi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-e04p5m5fbenb"
s3_prefix = "Test-karthi"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

