AWSTemplateFormatVersion: "2010-09-09"
Description: "App pipeline deployment notification common resources "

Parameters:
  AppEnvironment:
    Type: "String"
    Description: "App Environment"
    Default: karthi

Resources:
 
  AppPipelineArtifactBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join [
              "-",
              [
                "app-pipeline-artifacts",
                !Ref  AppEnvironment,
              ],
            ]