version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FirstTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nczw3190oli7"
s3_prefix = "FirstTest"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
