AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Content Related APIs

Resources:
  IotApiHttpGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Content API
      StageName: api
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"

  RefreshNavigationContent1:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ""
      MemorySize: 128
      AutoPublishAlias: live
      Timeout: 29
      DeploymentPreference:
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Policies:
        - AmazonSSMReadOnlyAccess
        - AmazonS3FullAccess
      Events:
        Api1:
          Type: Api
          Properties:
            Path: "/v1/navigation-content/refresh"
            Method: POST
            RestApiId:
              Ref: IotApiHttpGateway
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Task to periodically call content-api "api/v1/navigation-content/refresh".
            Enabled: True
      VpcConfig:
        SecurityGroupIds:
          - "{{resolve:ssm:ELASTICSEARCH_SUBNET_GROUP_ID:3}}"
        SubnetIds:
          - "{{resolve:ssm:ELASTICSEARCH_SUBNET_ID1:4}}"
 
  ContentCacheS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: "{{resolve:ssm:CONTENT_CACHE_S3_BUCKET:8}}"