name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  push:
    branches:
      - 'dev'
      - 'staging'
      - 'prod'
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  Deployment:
    runs-on: ubuntu-latest
    needs: test
    env:
      AWS_REGION: us-west-2
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Master
      run: echo $GITHUB_REF
      if: $GITHUB_REF == 'master'
    - name: Deploy Dev
      run: echo $GITHUB_REF
      if: $GITHUB_REF == 'dev'
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION