name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:

  push:
    branches:
      - 'dev'
      - 'staging'
      - 'prod'
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull-request' 
    steps:
      - name: Execute tests
        run: exit 0
  Deployment:
    runs-on: ubuntu-latest
    needs: test
    env:
      AWS_REGION: us-west-2
    if: github.event_name == 'push' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Set env NEED
        run: |
          if [[ $BRANCH == 'prod']] then
              echo "CONFIG=prod" >> "$GITHUB_ENV"
          elif [[ $BRANCH == 'staging']] then
              echo "CONFIG=staging" >> "$GITHUB_ENV"
          elif [[ $BRANCH == 'dev1']] then
              echo "CONFIG=dev1" >> "$GITHUB_ENV"
          fi
      - name: Branch COnfig
        run: echo 'The branch config is' $CONFIG













      # - name: Set Prod Environment variables
      #   run: echo  ${GITHUB_REF##*/}
      #   if:  ${GITHUB_REF##*/} == 'prod'
      # - name: Set Master Environment variables
      #   run: echo  ${GITHUB_REF##*/}
      #   if:  ${GITHUB_REF##*/} == 'master'
      # - name: Branch name
      #   run: echo running on branch ${GITHUB_REF##*/}
    # steps:
    # - uses: actions/checkout@v2
    # - uses: nelonoel/branch-name@v1
   
   
    # - name: Get branch name
    #   run: echo 'The branch name is' $BRANCH_NAME
    # - name: Configure AWS credentials
    #   id: creds
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{env.AWS_REGION}}
    
