
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Multi stage deployment test

Resources:
  TestAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Test API
      StageName: PROD3

  DeploymentProd:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: 
        Ref: TestAPI
      Description: My deployment

  Prod1:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod3
      Description: Prod
      RestApiId:
        Ref: TestAPI
      DeploymentId: 
        Ref: DeploymentProd

  GetContent1:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ""
      MemorySize: 128
      AutoPublishAlias: live
      Timeout: 15
      Policies:
        - AmazonSSMReadOnlyAccess
      Events:
        Api1:
          Type: Api
          Properties:
            Path: "/v1/content/{className}/{id}"
            Method: GET
            RequestParameters:
              - method.request.path.id:
                  Caching: true
              - method.request.path.className:
                  Caching: true
            RestApiId:
              Ref: TestAPI
  GetContentScalableTarget1:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 100
      MinCapacity: 1
      ResourceId: !Sub function:${GetContent1}:live
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
    DependsOn: GetContent1Aliaslive
  GetContentScalingPolicy1:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref GetContentScalableTarget1
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.70
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization

  
  ContentCacheS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: "{{resolve:ssm:CONTENT_CACHE_S3_BUCKET:1}}"
